<font size = 4 face = "黑体">

当CheckedException产生时，不一定立刻处理它，可以再把异常throws出去。

在方法中使用try-catch-finally是由这个方法来处理异常。但是在一些情况下，当前方法并不需要处理发生的异常，而是向上传递给调用它的方法处理。

如果一个方法中可能产生某种异常，但是并不能确定如何处理这种异常，则应根据异常规范在方法的首部声明该方法可能抛出的异常。

如果一个方法抛出多个已检查异常，就必须在方法的首部列出所有的异常，之间以逗号隔开。

```java
package yzy.exception;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

/*
 * 继承关系 FileNotFoundException -> IOException,所以只需要抛出父类IOException异常就好了,也可以用逗号隔开都写上
 * 抛出异常后最终由JRE来处理
 */
public class testThrows {
	public static void main(String[] args) throws IOException,FileNotFoundException{
		FileReader reader = null;
		reader = new FileReader("D:/testTryCatch.txt");
		char c1 = (char)reader.read();  //reader返回第一个字符(以int类型返回)
		System.out.println(c1);
		
			if(reader != null) {  //异常处理
				reader.close();
			}
		
	}
}
```

</br>

总结: </br>
如果多个异常需要同时抛出,并且异常之间是继承关系,可以只抛出父类异常,只抛父类异常也同时满足子类异常抛出的(和try-catch一样可以只写父类异常偷懒),也可以将父子异常用逗号隔开都写上




</font>